### ISSUE TITLE
Fly Bypass

### ISSUE THREAD

**Issue by ArrowReport** [MC-Jinky/Cenix#1]
LiquidBounce -> Fly -> AACv3Fast

Flags sometimes but, you can keep flying because the Anticheat Flags not often enough

**Comment by jonathannargi** [comment]
Cenix is now 1.13 only and will no longer be updated for previous versions.

LiquidBounce is not a 1.13 client, so testing for this cannot be done.

**Comment by MC-Jinky** [comment]
Cenix is now for 1.13 and will no longer be updated for previous versions of minecraft.

LiquidBounce does not support 1.13, so I cannot further test on this issue for the new version.

**Comment by coolpvpv** [comment]
> Cenix is now for 1.13 and will no longer be updated for previous versions of minecraft.
> 
> LiquidBounce does not support 1.13, so I cannot further test on this issue for the new version.

this was from 2018 sep 19 xd
