### ISSUE TITLE
alot of bypasses and a little bit of falses

### ISSUE THREAD

**Issue by coolpvpv** [MC-Jinky/Cenix#2]
this is on the impact 1.13.2 client heres link to the client https://impactdevelopment.github.io/ but the modules that work are fly mode mineplex and you have to hold sneak when you use mineplex fly or you could hold sneak and jump so you go down and up ghost hand works but not to open the chest the opening for chests doesn't work but you can still break the chest through the blocks the blink detection doesn't work i blink all the from the start of my chunk to the end of it and it doesn't set off any alerts and fly mode 3d any speed set works fly mode aac works fly mode glide works you can use elytra+ module on impact to fly infinitely without flagging back at all and speed mode bhop works and the config is glitched cause when i loaded the anticheat i was going to go into the config to edit some stuff and all it says in the config is cenix and speed mode vhop works speed mode lowhop works and you can use speed mode float to fly for 25 blocks until it flags fly so you should fix / improve that and speed mode strafe works set the multiplier to 5 and then hold spacebar when you speed around cause it flags when its on the ground so when you hold spacebar it makes it bypass and when you ride a horse and you jump sometimes it will flag fly clicktp works btw longjump mode normal and the speed set to anything under 16 bypasses and longjump mode nodamage works and airjump works just hold spacebar when you have airjump on and when you ride a boat it falses fly spider works and you need to add a timer check cause any could just use timer as a speed and i think thats it xd

**Comment by MC-Jinky** [comment]
Thank you for informing me, I will begin testing on the impact 1.13.2 client and testing with the information you have given me.

It's stated on the Spigot page that Blink partially works, I've tested it with a different client and it blocks if depending on how far you attempt to travel. Every hacked client tends to do things differently.

**Comment by MC-Jinky** [comment]
Current Progress:

- Mineplex Flight has been blocked
- 3D Flight has been blocks
