### ISSUE TITLE
some falses and bypasses again lol this is on 1.13.2 btw

### ISSUE THREAD

**Issue by coolpvpv** [MC-Jinky/Cenix#3]
stack up 30 blocks in the air then have elytra on this is 1.13.2 btw you glide down then try to fly up with the elytra and that will false it and fireworks used to boost you in elytra also falses fly and you can false speed with elytra put a elytra on then walk diagonal and spam jump so you get like a little boost from the elytra and after a few trys it should false speed and i found this weird false when i was swimming in the water with elytra on it sometimes falses fly idk why and heres another fly false that i dont really know how to explain so heres a video of it and impacts speed mode vhop bhop and lowhop still bypass and impacts riding module for horses and pigs works the entity speed and entity step work and the other settings in there bypass on max settings so you should fix that

**Comment by MC-Jinky** [comment]
Fixed
