### ISSUE TITLE
some bypasses on 1.13.2 aristois

### ISSUE THREAD

**Issue by coolpvpv** [MC-Jinky/Cenix#4]
download the 1.13.2 version on here https://aristois.net/download
glide module bypasses the horsefly in the flight module works and if you use glide with fly you can glide super fastly but turn on glide first then have it glide then turn on fly then you go fast and the bhop module set to speed 4 or under works and the speed module set to its default values works but you have to hold spacebar cause it flags when you use it as a onground speed instead of a bhop and the jesus module works with the anticheat bypass mode off and on

**Comment by MC-Jinky** [comment]
Mostly fixed. Water Walk detection is being updated soon.
