### ISSUE TITLE
Some speed and fly falses and boatfly false flag this is on 1.13.2 btw

### ISSUE THREAD

**Issue by coolpvpv** [MC-Jinky/Cenix#5]
when you sprint and jump up stairs it falses speed if you get alot of ice put it down then put blocks above it then get to edge of the block where you can still jump under the block and run and keep doing that on the edge it will for some reason false speed and if you jump on slime from a high place it will false fly and you can sometimes false speed with blocks above your head and ice on the ground and keep going until you get to the end then once your close to the end you want to hit jump right before your going to get off the ice and that will sometimes false speed and heres another way to false speed with ice put trapdoors on the head blocks then you can spam jump and go super fast and it will sometimes false speed and you can false fly by going to a ocean wheres there water then places alot of signs down and sometimes when you go through the signs it will false fly and you can false boatfly by stacking up like 5 blocks put a platform down and then put the boat on it then slowly ride the boat to the edge and when you fall it falses boatfly and you false boatfly by putting water down a hill like this https://imgur.com/eAcbSHa then ride down a boat on it and it will flag boatfly and if you get stuck in the air it will flag fly to

**Comment by MC-Jinky** [comment]
Fixed
