### ISSUE TITLE
Some bypasses on wwe client this is on 1.13.2 btw and some falses

### ISSUE THREAD

**Issue by coolpvpv** [MC-Jinky/Cenix#7]
heres link to the client https://wweclient.com/Download.php speed mode fasthop works hop works tomato works packet works strafe works and bhop works packetfly mode fast works and you have to set the speed to 0.17 or less for it to bypass and if you have knockback 1 or 2 on your sword and you hit players sometimes it will false speed and if you give a player levitation it will false the fly check

**Comment by MC-Jinky** [comment]
Fixed in newer versions.
