### ISSUE TITLE
[Not a issue] Question

### ISSUE THREAD

**Issue by ODazzahO** [MC-Jinky/Cenix#8]
Is there any plans for bungee compatibility, so reports are sent to staff no matter what server they are on within the network?

**Comment by MC-Jinky** [comment]
It's on the list, but it's not that high of a priority. I'm more focused on getting the anticheat to have fewer false calls & become more accurate at what it currently detects, and what it has the ability to detect in the future.

Most likely, the bungeecord support would require you to have a permissions plugin on the bungeecord server, and it would probably hook in with that.
